import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {ReactNode} from "react";
// import otherPage from "./other.module.css"; // Ensure the correct relative path

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Yet 2.0",
    description: "Generated by create next app"
};

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {

    return (
        <html lang="en">
            <body className={inter.className}>
                <nav>
                    <div>
                        <a href="/commands">Commands</a>
                        <a href="/tos">ToS</a>
                    </div>
                    <div>
                        <picture>
                            <img src="/Banner.png" alt="Banner" id="img" />
                        </picture>
                    </div>
                    <div>
                        <a href="https://discord.gg/r2rdHXTJvs" target="_blank">Support</a>
                        <a
                            href="https://discord.com/oauth2/authorize?client_id=701280304182067251&permissions=412317141056&scope=applications.commands%20bot"
                            target="_blank"
                        >
                            Invite
                        </a>
                    </div>
                </nav>
                {children}
            </body>
        </html>
    );
}