import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import home from "./page.module.css";
// import otherPage from "./other.module.css"; // Ensure the correct relative path

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Yet 2.0",
    description: "Generated by create next app"
};

// A function that checks the current path and returns the appropriate class name
const getNavbarClass = (pathname: string) => {
    if (pathname === "/") {
        return home.navbar;
    // } else if (pathname === "/otherPage") {
        // return otherPage.navbar;
    } else {
        return "";
    }
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const navbarClass = home.img;
    // const navbarClass = getNavbarClass(headers().get('domain') || ""); // Get the appropriate class

    return (
        <html lang="en">
            <body className={inter.className}>
                <nav>
                    <div>
                        <a href="/commands">Commands</a>
                        <a href="/tos">ToS</a>
                    </div>
                    <div>
                        <picture>
                            <img src="/Banner.png" alt="Banner" id="img" className={navbarClass} />
                        </picture>
                    </div>
                    <div>
                        <a href="https://discord.gg/r2rdHXTJvs" target="_blank">Support</a>
                        <a
                            href="https://discord.com/oauth2/authorize?client_id=701280304182067251&permissions=412317141056&scope=applications.commands%20bot"
                            target="_blank"
                        >
                            Invite
                        </a>
                    </div>
                </nav>
                {children}
            </body>
        </html>
    );
}
