import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {ReactNode} from "react";
import Particles from "./_components/Particles";
// import otherPage from "./other.module.css"; // Ensure the correct relative path

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Yet 2.0",
    description: "Generated by create next app"
};

function Navbar() {
    return (
        
        <nav>
            <div>
                <a href="/">
                <picture>
                    <img src="/Banner.png" alt="Banner" id="img" />
                </picture>
                </a>
            </div>
            <div>
                <a href="/commands">Commands</a>
                <a href="/tos">ToS</a>
                <a href="/pp">Privacy Policy</a>
                <a href="https://discord.gg/r2rdHXTJvs" target="_blank">Support</a>
                <a
                    href="https://discord.com/oauth2/authorize?client_id=701280304182067251&permissions=412317141056&scope=applications.commands%20bot"
                    target="_blank"
                >
                    Invite
                </a>
            </div>
        </nav>
    )
}

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {

    return (
        <html lang="en">
            <body className={inter.className}>
                <Navbar />
                {children}
                <footer>
                    <div className="copyright">
                        <center>
                            &copy;2024 Yet 2.0 Bot. All rights reserved.
                        </center>
                    </div>
                </footer>
            <div id="background">
                <Particles />
            </div>
            </body>
        </html>
    );
}